export const allTests = [
  {
    "id": "a1/01",
    "legacyId": "A1-test-1",
    "level": "a1",
    "num": 1,
    "variant": 1,
    "title": "Тест A1 — Вариант 1",
    "minutes": 20,
    "maxPoints": 40,
    "passPercent": 70,
    "questionCount": 36
  },
  {
    "id": "a1/02",
    "legacyId": "A1-test-2",
    "level": "a1",
    "num": 2,
    "variant": 2,
    "title": "Тест A1 — Вариант 2",
    "minutes": 20,
    "maxPoints": 40,
    "passPercent": 70,
    "questionCount": 36
  },
  {
    "id": "a1/03",
    "legacyId": "A1-test-3",
    "level": "a1",
    "num": 3,
    "variant": 3,
    "title": "Тест A1 — Вариант 3",
    "minutes": 20,
    "maxPoints": 40,
    "passPercent": 70,
    "questionCount": 36
  },
  {
    "id": "a2/01",
    "legacyId": "A2-test-1",
    "level": "a2",
    "num": 1,
    "variant": 1,
    "title": "Тест A2 — Вариант 1",
    "minutes": 30,
    "maxPoints": 48,
    "passPercent": 70,
    "questionCount": 42
  },
  {
    "id": "a2/02",
    "legacyId": "A2-test-2",
    "level": "a2",
    "num": 2,
    "variant": 2,
    "title": "Тест A2 — Вариант 2",
    "minutes": 30,
    "maxPoints": 48,
    "passPercent": 70,
    "questionCount": 42
  },
  {
    "id": "a2/03",
    "legacyId": "A2-test-3",
    "level": "a2",
    "num": 3,
    "variant": 3,
    "title": "Тест A2 — Вариант 3",
    "minutes": 30,
    "maxPoints": 48,
    "passPercent": 70,
    "questionCount": 42
  },
  {
    "id": "b1/01",
    "legacyId": "B1-test-1",
    "level": "b1",
    "num": 1,
    "variant": 1,
    "title": "Тест B1 — Вариант 1",
    "minutes": 40,
    "maxPoints": 55,
    "passPercent": 70,
    "questionCount": 50
  },
  {
    "id": "b1/02",
    "legacyId": "B1-test-2",
    "level": "b1",
    "num": 2,
    "variant": 2,
    "title": "Тест B1 — Вариант 2",
    "minutes": 40,
    "maxPoints": 55,
    "passPercent": 70,
    "questionCount": 50
  },
  {
    "id": "b1/03",
    "legacyId": "B1-test-3",
    "level": "b1",
    "num": 3,
    "variant": 3,
    "title": "Тест B1 — Вариант 3",
    "minutes": 40,
    "maxPoints": 55,
    "passPercent": 70,
    "questionCount": 50
  },
  {
    "id": "b2/01",
    "legacyId": "B2-test-1",
    "level": "b2",
    "num": 1,
    "variant": 1,
    "title": "Тест B2 — Вариант 1",
    "minutes": 50,
    "maxPoints": 65,
    "passPercent": 70,
    "questionCount": 59
  },
  {
    "id": "b2/02",
    "legacyId": "B2-test-2",
    "level": "b2",
    "num": 2,
    "variant": 2,
    "title": "Тест B2 — Вариант 2",
    "minutes": 50,
    "maxPoints": 65,
    "passPercent": 70,
    "questionCount": 59
  },
  {
    "id": "b2/03",
    "legacyId": "B2-test-3",
    "level": "b2",
    "num": 3,
    "variant": 3,
    "title": "Тест B2 — Вариант 3",
    "minutes": 50,
    "maxPoints": 65,
    "passPercent": 70,
    "questionCount": 59
  },
  {
    "id": "knm/01",
    "legacyId": "knm-test-1",
    "level": "knm",
    "num": 1,
    "variant": 1,
    "title": "Тест KNM — Вариант 1",
    "minutes": 45,
    "maxPoints": 43,
    "passPercent": 70,
    "questionCount": 43
  },
  {
    "id": "knm/02",
    "legacyId": "knm-test-2",
    "level": "knm",
    "num": 2,
    "variant": 2,
    "title": "Тест KNM — Вариант 2",
    "minutes": 45,
    "maxPoints": 43,
    "passPercent": 70,
    "questionCount": 43
  },
  {
    "id": "knm/03",
    "legacyId": "knm-test-3",
    "level": "knm",
    "num": 3,
    "variant": 3,
    "title": "Тест KNM — Вариант 3",
    "minutes": 45,
    "maxPoints": 43,
    "passPercent": 70,
    "questionCount": 43
  }
];
